name: Windows

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        mode: [Debug, Release, Profiling]
        arch: [x64]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.mode }}-${{ matrix.arch }}
        cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
          actions-cache-folder: .xmake-cache-${{ matrix.os }}-${{ matrix.mode }}-${{ matrix.arch }}

      - name: Update xmake repository
        run: xmake repo --update
      
      - name: Configure xmake and install dependencies
        run: |
          xmake f -y -p "windows" -a ${{ matrix.arch }} -m ${{ matrix.mode }} -c -vD

      - name: Compile
        run: |
          xmake -y -r -vD
