name: Windows

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        mode: [Debug, Development, Shipping, Profiling]
        arch: [x64]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.mode }}-${{ matrix.arch }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: 'windows'
          package-cache: true
          package-cache-key: 'windows'
          project-path: 'DragonForge-Engine'
          build-cache: true
          build-cache-key: 'windows'

      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 8GB
          maximum-size: 32GB
          disk-root: "D:"

      - name: Compiling Test
        run: |
          xrepo add-repo MyFork https://github.com/Cappecasper03/xmake-repo.git
          xmake --version
          xmake f -y -p "windows" -a ${{ matrix.arch }} -m ${{ matrix.mode }} -vD -c
          xmake -vD -r
