name: Windows

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        mode: [Debug, Release, Profiling]
        arch: [x64]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.mode }}-${{ matrix.arch }}
        cancel-in-progress: true

    steps:
      - name: Get current date as package key
        id: cache_key
        run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

      - name: Define Standard Xmake Packages Path
        id: xmake_paths
        shell: pwsh
        run: |
          $xmakePackagesDir = Join-Path $env:LOCALAPPDATA ".xmake\packages"
          echo "XMAKE_PACKAGES_DIR=$xmakePackagesDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "Xmake packages directory set to: $xmakePackagesDir"

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: .xmake-cache-${{ steps.cache_key.outputs.key }}

      - name: Update xmake repo
        run: |
          xmake repo -u

      - name: Restore cached xmake dependencies
        id: restore-depcache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.XMAKE_PACKAGES_DIR }}/.xmake/packages
          key: ${{ matrix.os }}-${{ steps.cache_key.outputs.key }}
          restore-keys: |
            ${{ matrix.os }}-

      - name: Enable git long paths
        run: git config --global core.longpaths true

      - name: Configure xmake and install dependencies
        run: |
          xmake f -y -p "windows" -a ${{ matrix.arch }} -m ${{ matrix.mode }} -vD -c

      - name: Save cached xmake dependencies
        if: ${{ !steps.restore-depcache.outputs.cache-hit }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.XMAKE_PACKAGES_DIR }}/.xmake/packages
          key: ${{ steps.restore-depcache.outputs.cache-primary-key }}
  
      - name: Compile
        run: |
          xmake -y -vD -r
