name: Windows

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        mode: [Debug, Release, Profiling]
        arch: [x64]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.mode }}-${{ matrix.arch }}
        cancel-in-progress: true

    steps:
      - name: Get current date as package key
        id: cache_key
        run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/checkout@v4

      - name: Set xmake env
        run: echo "XMAKE_GLOBALDIR=xmake-global" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: .xmake-cache-W${{ steps.cache_key.outputs.key }}

      - name: Update xmake repo
        run: |
          xmake repo -u

      - name: Retrieve dependencies hash
        id: dep_hash
        run: echo "hash=$(xmake l utils.ci.packageskey)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      
      - name: Configure xmake and install dependencies
        run: |
          xmake f -y -p "windows" -a ${{ matrix.arch }} -m ${{ matrix.mode }} -vD -c
  
      - name: Compile
        run: |
          xmake -vD -r
